### ISSUE TITLE
Roadmap: editpress plugins

### ISSUE THREAD

**Issue by veaba** [editpress-org/editpress#1]
### vuepress-plugind-ediable
- [ ] shiki
- [ ] markdown-it
- [ ] no auth guide for client 

### vitepress-plugind-ediable
- [ ] shiki
- [ ] markdown-ite
- [ ] no auth guide for client 

### rspress-plugind-ediable
- [ ] shiki
- [ ] markdown-ite
- [ ] no auth guide for client
